alias(
    name = "EGPayWallAssets",
    actual = "//exteraGram/messenger/paywall:EGPayWallAssets",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGPayWall",
    actual = "//exteraGram/messenger/paywall:paywall",
    visibility = ["//visibility:public"],
)
