alias(
    name = "EGPluginEngineBridge",
    actual = "//exteraGram/messenger/plugins:EGPluginEngineBridge",
    visibility = ["//visibility:public"],
)

alias(
    name = "PythonSDK",
    actual = "//exteraGram/messenger/plugins:PythonSDK",
    visibility = ["//visibility:public"],
)

alias(
    name = "SamplePlugins",
    actual = "//exteraGram/messenger/plugins:SamplePlugins",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGPythonExtensionsStub",
    actual = "//exteraGram/messenger/plugins:EGPythonExtensionsStub",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGBeewarePackagesStub",
    actual = "//exteraGram/messenger/plugins:EGBeewarePackagesStub",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGPluginEngine",
    actual = "//exteraGram/messenger/plugins:plugins",
    visibility = ["//visibility:public"],
)
