alias(
    name = "EGNY",
    actual = "//exteraGram/messenger/components:EGNY",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGNYAssets",
    actual = "//exteraGram/messenger/components:EGNYAssets",
    visibility = ["//visibility:public"],
)
