alias(
    name = "EGStrings",
    actual = "//exteraGram/messenger/strings:strings",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGLocalizableStrings",
    actual = "//exteraGram/messenger/strings:EGLocalizableStrings",
    visibility = ["//visibility:public"],
)
