alias(
    name = "EGUIAssets",
    actual = "//exteraGram/messenger/preferences:EGUIAssets",
    visibility = ["//visibility:public"],
)

alias(
    name = "EGSettingsUI",
    actual = "//exteraGram/messenger/preferences:preferences",
    visibility = ["//visibility:public"],
)
